apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: prometheus
resources:
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - service.yaml
# https://prometheus.io/docs/prometheus/latest/querying/basics/
# https://medium.com/@vinoji2005/install-prometheus-on-kubernetes-tutorial-and-example-6b3c800e7e1c