"global":
  "http_config":
    "proxy_from_environment": true
"inhibit_rules":
- "equal":
  - "namespace"
  - "alertname"
  "source_matchers":
  - "severity = critical"
  "target_matchers":
  - "severity =~ warning|info"
- "equal":
  - "namespace"
  - "alertname"
  "source_matchers":
  - "severity = warning"
  "target_matchers":
  - "severity = info"
"receivers":
- "name": "Default"
  discord_configs:
    - webhook_url: >-
          <DEFAULT_WEBHOOK_URL>
      message: |-
          {{ range .Alerts.Firing }}
              Alert: **{{ printf "%.150s" .Annotations.summary }}** ({{ .Labels.severity }})
              Description: {{ printf "%.150s" .Annotations.description }}
              Alertname: {{ .Labels.alertname }}
              Namespace: {{ .Labels.namespace }}
              Service: {{ .Labels.service }}
          {{ end }}

          {{ range .Alerts.Resolved }}
              Alert: **{{ printf "%.150s" .Annotations.summary }}** ({{ .Labels.severity }})
              Description: {{ printf "%.150s" .Annotations.description }}
              Alertname: {{ .Labels.alertname }}
              Namespace: {{ .Labels.namespace }}
              Service: {{ .Labels.service }}
          {{ end }}
- "name": "Watchdog"
  discord_configs:
    - webhook_url: >-
          <WATCHDOG_WEBHOOK_URL>
      message: |-
          {{ range .Alerts.Firing }}
              Alert: **{{ printf "%.150s" .Annotations.summary }}** ({{ .Labels.severity }})
              Description: {{ printf "%.150s" .Annotations.description }}
              Alertname: {{ .Labels.alertname }}
              Namespace: {{ .Labels.namespace }}
              Service: {{ .Labels.service }}
          {{ end }}

          {{ range .Alerts.Resolved }}
              Alert: **{{ printf "%.150s" .Annotations.summary }}** ({{ .Labels.severity }})
              Description: {{ printf "%.150s" .Annotations.description }}
              Alertname: {{ .Labels.alertname }}
              Namespace: {{ .Labels.namespace }}
              Service: {{ .Labels.service }}
          {{ end }}
- "name": "Critical"
  discord_configs:
    - webhook_url: >-
          <CRITICAL_WEBHOOK_URL>
      message: |-
          {{ range .Alerts.Firing }}
              Alert: **{{ printf "%.150s" .Annotations.summary }}** ({{ .Labels.severity }})
              Description: {{ printf "%.150s" .Annotations.description }}
              Alertname: {{ .Labels.alertname }}
              Namespace: {{ .Labels.namespace }}
              Service: {{ .Labels.service }}
          {{ end }}

          {{ range .Alerts.Resolved }}
              Alert: **{{ printf "%.150s" .Annotations.summary }}** ({{ .Labels.severity }})
              Description: {{ printf "%.150s" .Annotations.description }}
              Alertname: {{ .Labels.alertname }}
              Namespace: {{ .Labels.namespace }}
              Service: {{ .Labels.service }}
          {{ end }}
"route":
  "group_by":
  - "namespace"
  "group_interval": "5m"
  "group_wait": "30s"
  "receiver": "Default"
  "repeat_interval": "12h"
  "routes":
  - "matchers":
    - "alertname = Watchdog"
    "receiver": "Watchdog"
  - "matchers":
    - "severity = critical"
    "receiver": "Critical"