apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    iam.gke.io/gcp-service-account: gsm-accessor@okd-homelab.iam.gserviceaccount.com