apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-critical-alert
  namespace: openshift-monitoring
spec:
  groups:
  - name: test-critical-alert-group
    rules:
    - alert: TestCriticalAlert
      expr: vector(1) # always evaluates to true
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Test Critical Alert"
        description: "This is a test critical alert to verify Alertmanager configuration."