apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: community-kubevirt-hyperconverged
  namespace: kubevirt-hyperconverged
spec:
  channel: stable
  installPlanApproval: Manual # oc patch installplan install-xxxxx -n kubevirt-hyperconverged --type merge --patch '{"spec":{"approved":true}}'
  name: community-kubevirt-hyperconverged
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: kubevirt-hyperconverged-operator.v1.15.2
