apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: custom
  namespace: openshift-ingress-operator
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  idleConnectionTerminationPolicy: Deferred
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  domain: custom.okd.jenniferpweir.com
  nodePlacement:
    tolerations:
      - key: node-role.kubernetes.io/infra # should run on worker nodes; however, dont have enough workers so tolerate taint (HostNetwork publishes ingresscontroller endpoints directly on node where it is deployed, thus using up the same ports)
        operator: Exists
        effect: NoSchedule