kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/jennweir/HomeLab.git
    path: kubernetes/grafana-operator
    targetRevision: main
