kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: ingress-nginx
resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ingress-nginx-controller
    patch: |-
      - op: add
        path: /spec/replicas
        value: 2
