kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: metallb-system
resources:
  - ../../base
  - ip-addr-pool.yaml
  - rolebinding.yaml
patches:
  - target: 
      kind: Deployment
      name: controller
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value: 
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/infra
                      operator: Exists
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/infra
            operator: Exists
            effect: NoSchedule
  - target: 
      kind: DaemonSet
      name: speaker
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value: 
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: node-role.kubernetes.io/infra
                      operator: Exists
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/infra
            operator: Exists
            effect: NoSchedule