apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-anyuid-for-metallb-controller
  namespace: metallb-system
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: metallb-system
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-metallb-speaker-to-use-privileged-scc
  namespace: metallb-system
subjects:
  - kind: ServiceAccount
    name: speaker
    namespace: metallb-system
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
