apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-operator
  namespace: olm
  labels:
    app: argocd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-operator
  template:
    metadata:
      labels:
        app: argocd-operator
    spec:
      containers:
        - name: registry-server
          # https://argocd-operator.readthedocs.io/en/latest/install/olm/
          # https://quay.io/repository/argoprojlabs/argocd-operator-registry?tab=tags&tag=latest
          image: 
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          ports:
            - containerPort: 80
          env:
            - name: WATCH_NAMESPACE
              value: "argocd"
          ports:
            - name: grpc
              containerPort: 50051
          livenessProbe:
            exec:
              command:
                - grpcurl
                - -plaintext
                - localhost:50051
                - ping.Pinger/Ping
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - -addr=:50051