apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-operator
  namespace: olm
  labels:
    app: argocd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-operator
  template:
    metadata:
      labels:
        app: argocd-operator
    spec:
      containers:
        - name: registry-server
          image: quay.io/jennweir/argocd-operator:10.20.2024@sha256:03f93aec2ff1e6a73979f89e6d96426a55ecdada32b3272534d2aeae782a99c8
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          ports:
            - containerPort: 80
          env:
            - name: WATCH_NAMESPACE
              value: "argocd"
          ports:
            - name: grpc
              containerPort: 50051
          livenessProbe:
            exec:
              command:
                - grpcurl
                - -plaintext
                - localhost:50051
                - ping.Pinger/Ping
          readinessProbe:
            exec:
              command:
                - grpc_health_probe
                - -addr=:50051