apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-cert
  namespace: pihole
spec:
  secretName: pihole-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "pihole.homelab.jenniferpweir.comh"
  dnsNames:
    - "pihole.homelab.jenniferpweir.com"
