apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc-pihole-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/pihole-etc-pihole"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc-dnsmasq-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/pihole-etc-dnsmasq"
