apiVersion: v1
kind: Secret
metadata:
  name: pihole-password
  namespace: pihole
type: Opaque
data:
  WEBPASSWORD:  # base64 encoded # didnt work; ended up removing password
  # kubectl exec -it pihole-0 -n pihole -- /bin/bash
  # sudo pihole setpassword