---
- name: Deploy only the install-k8s.yaml file to raspberry pi
  hosts: pis
  tasks:
  - name: Upload install script
    ansible.builtin.copy:
      src: /playbooks/raspberry-pis/install-k8s.yaml
      dest: /tmp/install-k8s.yaml

  - name: Run install playbook
    ansible.builtin.command: ansible-playbook /tmp/install-k8s.yaml
