---
- name: Playbook to install main node k8s on raspberry pis
  hosts: k8s_main
  become: yes
  tasks:
  # - name: Create the .kube directory
  #   ansible.builtin.file:
  #     path: "{{ ansible_env.HOME }}/.kube"
  #     state: directory
  #     mode: '0755'

  # - name: Copy admin.conf to .kube/config
  #   ansible.builtin.command:
  #     cmd: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  #   become: yes

  # - name: Change ownership of the config file
  #   ansible.builtin.command:
  #     cmd: chown $(id -u):$(id -g) $HOME/.kube/config
  #   become: yes

  # sudo rm -rf /root/.kube/config
  # sudo cp /etc/kubernetes/admin.conf /root/.kube/config
  # sudo chown root:root /root/.kube/config
  # sudo chmod 600 /root/.kube/config
  
  - name: Apply flannel to the cluster
    ansible.builtin.shell: |
      kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    become: no

  - name: Install cert-manager
    ansible.builtin.shell: |
      kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.2/cert-manager.yaml

  - name: Apply metalLB manifest
    ansible.builtin.shell: |
      kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml

  - name: Configure metalLB
    ansible.builtin.shell: |
      cat <<EOF | kubectl apply -f -
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 10.0.0.200-10.0.0.250
      ---
      EOF
    become: no

  - name: Install argocd
    ansible.builtin.shell: |
      kubectl create namespace argocd
      kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    become: no

  - name: Change the argocd-server service type to LoadBalancer
    ansible.builtin.shell: |
      kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "LoadBalancer"}}'
    become: no

  - name: Deploy k8s dashboard
    ansible.builtin.shell: |
      kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
    become: no

  # - name: Copy cluster-issuer.yaml to main pi
  #   ansible.builtin.copy:
  #     src: /Users/jenn/Projects/HomeLab/kubernetes/argocd/cluster-issuer.yaml
  #     dest: /tmp/cluster-issuer.yaml

  # - name: Apply cluster-issuer manifest
  #   command: kubectl apply -f /tmp/cluster-issuer.yaml

  # - name: Copy ingress.yaml to main pi
  #   ansible.builtin.copy:
  #     src: /Users/jenn/Projects/HomeLab/kubernetes/argocd/ingress.yaml
  #     dest: /tmp/ingress.yaml
  
  # - name: Apply ingress manifest
  #   command: kubectl apply -f /tmp/ingress.yaml

  # - name: Add nginx controller help repository
  #   ansible.builtin.shell: |
  #     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
  #     helm repo update

  # - name: Install nginx ingress controller
  #   ansible.builtin.shell: |
  #     helm install nginx-ingress ingress-nginx/ingress-nginx \
  #     --namespace ingress-nginx --create-namespace