---
- name: Playbook to install main node k8s on raspberry pis
  hosts: k8s_main
  become: yes
  tasks:
  # - name: Create the .kube directory
  #   ansible.builtin.file:
  #     path: "{{ ansible_env.HOME }}/.kube"
  #     state: directory
  #     mode: '0755'

  # - name: Copy admin.conf to .kube/config
  #   ansible.builtin.command:
  #     cmd: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  #   become: yes

  # - name: Change ownership of the config file
  #   ansible.builtin.command:
  #     cmd: chown $(id -u):$(id -g) $HOME/.kube/config
  #   become: yes

  # sudo rm -rf /root/.kube/config
  # sudo cp /etc/kubernetes/admin.conf /root/.kube/config
  # sudo chown root:root /root/.kube/config
  # sudo chmod 600 /root/.kube/config
  
  - name: Apply flannel to the cluster
    ansible.builtin.shell: |
      kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    become: no

  - name: Install cert-manager
    ansible.builtin.shell: |
      kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.yaml
    become: no

  - name: Apply metalLB manifest
    ansible.builtin.shell: |
      kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.14.8/config/manifests/metallb-native.yaml
    become: no

  - name: Install argocd
    ansible.builtin.shell: |
      kubectl create namespace argocd
      kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    become: no

  - name: Deploy k8s dashboard
    ansible.builtin.shell: |
      kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
    become: no

  - name: Install nginx ingress controller
    ansible.builtin.shell: |
      kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/cloud/deploy.yaml
    become no
