apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - customresourcedefinition.yaml
  - deployment-argocd-applicationset-controller.yaml
  - deployment-argocd-dex-server.yaml
  - deployment-argocd-notifications-controller.yaml
  - deployment-argocd-redis.yaml
  - deployment-argocd-repo-server.yaml
  - deployment-argocd-server.yaml
  - networkpolicy.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
