# https://github.com/okd-project/okd/releases
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    name: version
  spec:
    channel: stable-scos-4
    clusterID: <CLUSTER_ID>
    desiredUpdate:
      force: false
      image: quay.io/okd/scos-release@sha256:67c61cd207658fb02d7021ff53d08855f6c90748f1647a4071ce52a7bf53fa96
      version: 4.18.0-okd-scos.9
    upstream: https://amd64.origin.releases.ci.openshift.org/graph
kind: List
metadata: {}