# https://github.com/okd-project/okd/releases
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    name: version
  spec:
    channel: stable-scos-4
    clusterID: <path:projects/1086456784694/secrets/okd_cluster_id#okd_cluster_id>
    desiredUpdate:
      force: false
      image: registry.ci.openshift.org/origin/release-scos@sha256:58fbb82cb873eb7aad82307970951b4536f559d547b9bde2e8e888c2efe1e626
      version: 4.19.0-okd-scos.0
    upstream: https://amd64.origin.releases.ci.openshift.org/graph
kind: List
metadata: {}