# https://github.com/okd-project/okd/releases
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    name: version
  spec:
    channel: stable-scos-4
    clusterID: <CLUSTER_ID>
    desiredUpdate:
      force: false
      image: quay.io/okd/scos-release@sha256:25f7fdc4fe98e129858ff1bcd2e71269743b50b3087feab0f0cc9de2213680f9
      version: 4.20.0-okd-scos.ec.16
    upstream: https://amd64.origin.releases.ci.openshift.org/graph
kind: List
metadata: {}