apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: okd-cluster-id-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gsm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cluster-id
    creationPolicy: Owner
  data:
    - secretKey: okd_cluster_id
      remoteRef:
        key: okd_cluster_id
        version: "latest"
