apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/default-logs-container: manager
    olm.operatorframework.io/feature-set: standard
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  name: catalogd-controller-manager
  namespace: olmv1-system
spec:
  minReadySeconds: 5
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      control-plane: catalogd-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        olm.operatorframework.io/feature-set: standard
      labels:
        app.kubernetes.io/name: catalogd
        control-plane: catalogd-controller-manager
        app.kubernetes.io/part-of: olm
    spec:
      containers:
        - args:
            - --leader-elect
            - --metrics-bind-address=:7443
            - --external-address=catalogd-service.olmv1-system.svc
            - --feature-gates=APIV1MetasHandler=false
            - --tls-cert=/var/certs/tls.crt
            - --tls-key=/var/certs/tls.key
            - --pull-cas-dir=/var/ca-certs
          command:
            - ./catalogd
          image: quay.io/operator-framework/catalogd:v1.11.0-amd64@sha256:51de08d18ed25e17704c661809e4650855de5f23c3dcc10825785e340713ae42
          name: manager
          livenessProbe:
            httpGet:
              path: /healthz
              port: probe
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: probe
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
          volumeMounts:
            - mountPath: /var/cache/
              name: cache
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/certs
              name: catalogserver-certs
            - mountPath: /var/ca-certs
              name: ca-certs
              readOnly: true
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          terminationMessagePolicy: FallbackToLogsOnError
          ports:
            - name: https
              containerPort: 8443
            - name: webhook
              containerPort: 9443
            - name: metrics
              containerPort: 7443
            - name: probe
              containerPort: 8081
      serviceAccountName: catalogd-controller-manager
      volumes:
        - emptyDir: {}
          name: cache
        - emptyDir: {}
          name: tmp
        - name: catalogserver-certs
          secret:
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
            optional: false
            secretName: catalogd-service-cert-v1.11.0
        - name: ca-certs
          secret:
            items:
              - key: ca.crt
                path: olm-ca.crt
            optional: false
            secretName: catalogd-service-cert-v1.11.0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/control-plane: ""
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
