apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yaml
  - clusterissuer.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - customresourcedefinition.yaml
  - deployment-catalogd-controller-manager.yaml
  - deployment-operator-controller-controller-manager.yaml
  - issuer.yaml
  - mutatingwebhookconfiguration.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml
  - validatingadmissionpolicy.yaml
  - validatingadmissionpolicybinding.yaml
