apiVersion: v1
kind: ConfigMap
metadata:
  name: google-creds
  namespace: argocd
data:
  credentials_config.json: |
    {
      "credential_source": {
        "file": "/var/run/secrets/kubernetes.io/serviceaccount/token",
        "format": {
          "type": "text"
        }
      },
      "audience": "//iamcredentials.googleapis.com/projects/494599251997/locations/global/workloadIdentityPools/k8s-wif-pool/providers/k8s-wif-service-account",
      "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/k8s-wif-service-account:generateAccessToken",
      "type": "external_account",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token"
    }
