apiVersion: v1
kind: Node
metadata:
  name: worker-4.okd.jenniferpweir.com
  labels:
    node-role.kubernetes.io/infra: ""
spec:
  taints:
    - key: node-role.kubernetes.io/infra
      effect: NoSchedule