apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gsm-cluster-secret-store
  namespace: external-secrets-operator
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: credentials.json
            namespace: external-secrets-operator
      projectID: pi-cluster-433101