apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  # https://github.com/stefanprodan/podinfo
  namespace: podinfo
resources:
  - deployment.yaml
  - hpa.yaml
  - namespace.yaml
  - service.yaml