apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: console-cert
  namespace: openshift-ingress
spec:
  secretName: console-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always # default
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - cert-manager
  dnsNames:
    - "*.apps.okd.jenniferpweir.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io