apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block-replicated
  resources:
    requests:
      storage: 8Gi