apiVersion: olm.operatorframework.io/v1
kind: ClusterExtension
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespace: argocd-operator
  source:
    sourceType: Catalog
    catalog:
      packageName: argocd-operator
      version: 0.18.0
  config:
    configType: Inline
    inline:
      deploymentConfig:
        env:
          - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
            value: "argocd"
