kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  project: default
  source:
    repoURL: https://github.com/jennweir/HomeLab.git
    path: manifests/platform/external-secrets-operator/overlays/okd
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m
        factor: 2
