kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kubevirt-hyperconverged
  namespace: kubevirt-hyperconverged
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kubevirt-hyperconverged
  project: default
  source:
    repoURL: https://github.com/jennweir/HomeLab.git
    path: manifests/platform/kubevirt-hyperconverged/overlays/okd
    targetRevision: main
  syncPolicy:
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m
        factor: 2