---
- name: Reset Kubernetes state on CoreOS nodes to prep for a re-install
  hosts: coreos_lab
  become: true
  gather_facts: false
  serial: 1
  tasks:
    - name: Reset kubeadm state
      ansible.builtin.command:
        cmd: kubeadm reset -f --cri-socket unix:///var/run/crio/crio.sock
      failed_when: false

    - name: Remove kubectl configuration directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /root/.kube
        - /home/core/.kube

    - name: Flush iptables rules and remove custom chains
      ansible.builtin.shell:
        cmd: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
      changed_when: true
      failed_when: false

    - name: Remove residual CNI configuration
      ansible.builtin.file:
        path: /etc/cni/net.d
        state: absent

    - name: Recreate empty CNI directory
      ansible.builtin.file:
        path: /etc/cni/net.d
        state: directory
        mode: "0755"
