apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-jenniferpweir-com
  namespace: cert-manager
spec:
  secretName: wildcard-jenniferpweir-com-tls
  issuerRef:
    name: jenniferpweir-com-issuer
    kind: ClusterIssuer
  commonName: "*.jenniferpweir.com"
  dnsNames:
  - "*.jenniferpweir.com"
  - "jenniferpweir.com"
