apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@jenniferpweir.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudDNS:
          project: pi-cluster
          hostedZoneName: 'argocd.jenniferpweir.com.'
          serviceAccountName:
            name: k8s-wif-service-account
            namespace: argocd