apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      imagePullSecrets:
        - name: quay-jennweir-pull-secret
      containers:
      - name: webserver
        image: quay.io/jennweir/custom-apache@sha256:236225be21ca4c6033e6cbfbd5a796783e958d4a3dfcae8dddfb71b2cbe63dcb
        ports:
        - containerPort: 80
