apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      imagePullSecrets:
        - name: quay-jennweir-pull-secret
      containers:
      - name: webserver
        image: quay.io/jennweir/custom-apache:2025.03.23@sha256:fe009576ab552372d71203964627f7082f39a7bda31102278ef521cab0ff441d
        lifecycle:
            postStart:
              exec:
                command: ["sh", "-c", 'sleep 10 && chmod 755 /usr/local/apache2/htdocs/*']
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/local/apache2/htdocs
          name: webserver-storage
      volumes:
        - name: webserver-storage
          persistentVolumeClaim:
            claimName: webserver-pvc
