apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-files
  namespace: webserver
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/webserver-files"