apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: webserver
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004