apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - crds.yaml
  - deployment.yaml
  - mutatingwebhook.yaml
  - namespace.yaml
  - rbac.yaml
  - service.yaml
