kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-operator
  project: default
  source:
    repoURL: https://github.com/jennweir/HomeLab.git
    path: manifests/platform/argocd/operator/applications
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m
        factor: 2