apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - customresourcedefinition.yaml
  - catalogsource.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - clusterserviceversion.yaml
  - deployment-catalog-operator.yaml
  - deployment-olm-operator.yaml
  - namespace.yaml
  - networkpolicy.yaml
  - olmconfig.yaml
  - operatorgroup.yaml
  - serviceaccount.yaml
