variant: fcos
version: 1.5.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAAok0q7jxMHMSUkp5vr6nzYB9A00gG8JZt41T+syFlft3Rv/LD4SswrhYiqAyfK3s+uGDobA8wwy7iUHrXAXAytqQHOU4bssijkJ73pGMZ6VqCBbH60PvXuvWwHS+VonPSndSSX4sQ1cGJjQdb86nLiAvIKfSFDgjUXYcMP7XZezM9eOg==
systemd:
  units:
    - name: hello.service
      enabled: true
      contents: |
        [Unit]
        Description=MyApp
        After=network-online.target
        Wants=network-online.target

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/bin/podman kill busybox1
        ExecStartPre=-/bin/podman rm busybox1
        ExecStartPre=/bin/podman pull busybox
        ExecStart=/bin/podman run --name busybox1 busybox /bin/sh -c "trap 'exit 0' INT TERM; while true; do echo Hello World; sleep 1; done"

        [Install]
        WantedBy=multi-user.target
    - name: containerd.service
      enabled: true
      dropins:
        - name: 99-proxy.conf
          contents: |
            [Service]
            EnvironmentFile=/etc/example-proxy.env
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: coreos-vm