apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../base
  - clusterissuer-staging.yaml
  - clusterissuer-prod.yaml
  - cloudflare-api-token.yaml
