apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gsm-secret-store
    kind: SecretStore
  target:
    name: oidc
    creationPolicy: Owner
  data:
    - secretKey: azure_client_secret
      remoteRef:
        key: azure_client_secret
