apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
  namespace: tailscale

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-role
  namespace: tailscale
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["tailscale-auth"] # name of tailscale secret (stored on cluster)
  verbs: ["get", "update", "patch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale-role-binding
  namespace: tailscale
subjects:
- kind: ServiceAccount
  name: tailscale
  namespace: tailscale
roleRef:
  kind: Role
  name: tailscale-role
  apiGroup: rbac.authorization.k8s.io
