apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbital-sync
  namespace: pihole
spec:
  selector:
    matchLabels:
      app: orbital-sync
  template:
    metadata:
      labels:
        app: orbital-sync
    spec:
      containers:
      - name: orbital-sync
        image: ghcr.io/mattwebbio/orbital-sync:sha-b7c105d-distroless@sha256:1a7e1963b457185337665204db1c1e553338d43a59b4ee2aeff4d070213b0289 #https://github.com/mattwebbio/orbital-sync/issues/190
        envFrom:
          - configMapRef:
              name: orbital-sync-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orbital-sync-config
  namespace: pihole
data:
  PRIMARY_HOST_BASE_URL: "http://pihole-0.pihole.pihole.svc.cluster.local"
  PRIMARY_HOST_PASSWORD: ""
  SECONDARY_HOST_1_BASE_URL: "http://pihole-1.pihole.pihole.svc.cluster.local"
  SECONDARY_HOSTS_1_PASSWORD: ""
  INTERVAL_MINUTES: "1"
