apiVersion: v1
baseDomain: jenniferpweir.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0 # install-config has 0 replicas for workers and workers added later
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: okd
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"<PLACEHOLDER>":{"auth":"<PULL-SECRET","email":"<EMAIL>"}}}'
sshKey: '<SSH-KEY>'