kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../base
  - certificate.yaml
  - clusterissuer.yaml
namespace: cert-manager
patches:
  - target:
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/1
        value:
          name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/run/secrets/tokens/gcp-ksa/credential-configuration.json
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - name: gcp-ksa
            mountPath: /var/run/secrets/tokens/gcp-ksa
            readOnly: true
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: gcp-ksa
            projected:
              defaultMode: 420
              sources:
                - serviceAccountToken:
                    audience: //iam.googleapis.com/projects/494599251997/locations/global/workloadIdentityPools/pi-cluster/providers/pi-cluster
                    expirationSeconds: 3600
                    path: token
                - configMap:
                    items:
                      - key: credential-configuration.json
                        path: credential-configuration.json
                    name: creds-config
                    optional: false
  - target:
      kind: ServiceAccount
      name: cert-manager
      namespace: cert-manager
    patch: |-
      - op: add
        path: /metadata/annotations/iam.gke.io~1gcp-service-account
        value: "cert-manager-dns-solver@pi-cluster-433101.iam.gserviceaccount.com"
configMapGenerator:
  - name: creds-config
    namespace: cert-manager
    options:
      disableNameSuffixHash: true
    files:
      - config/credential-configuration.json
